### ISSUE TITLE
Database deadlocks occasionally when writing

### ISSUE THREAD

**Issue by euan-forrester** [euan-forrester/photo-recommender#34]
From ingester-database:

```
Traceback (most recent call last):
File "./ingester-database/ingester-database.py", line 90, in <module>
write_batch(photo_batch, unwritten_message_batch)
File "./ingester-database/ingester-database.py", line 68, in write_batch
photo_batch
File "/ingester-database/databasebatchwriter.py", line 22, in batch_write
self.cursor.executemany(sql_insert, value_tuples)
File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor.py", line 675, in executemany
self.execute(operation, params)
File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor.py", line 569, in execute
self._handle_result(self._connection.cmd_query(stmt))
File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 553, in cmd_query
result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 442, in _handle_result
raise errors.get_exception(packet)
mysql.connector.errors.InternalError: 1213 (40001): Deadlock found when trying to get lock; try restarting transaction
```

**Comment by euan-forrester** [comment]
Maybe need to retry a few times?
