### ISSUE TITLE
ThrottlingException reading parameters

### ISSUE THREAD

**Issue by euan-forrester** [euan-forrester/photo-recommender#36]
Happened to be in ingester-database:

```
Traceback (most recent call last):
File "./ingester-database/ingester-database.py", line 43, in <module>
output_database_name = config_helper.get("output-database-name")
File "../common/confighelper.py", line 87, in get
value = self.ssm.get_parameter(Name=full_path, WithDecryption=is_secret)['Parameter']['Value']
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the GetParameter operation (reached max retries: 4): Rate exceeded
loop_command.sh: Finished command. Sleeping for 2
```

**Comment by euan-forrester** [comment]
Maybe need to cache these somehow?
