### ISSUE TITLE
DB sees too many connection errors

### ISSUE THREAD

**Issue by euan-forrester** [euan-forrester/photo-recommender#40]
Saw this go by from ingester-database:

```
Traceback (most recent call last):
File "./ingester-database/ingester-database.py", line 65, in <module>
max_retries=output_database_max_retries)
File "/ingester-database/databasebatchwriter.py", line 7, in __init__
self.cnx = mysql.connector.connect(user=username, password=password, host=host, port=port, database=database)
File "/usr/local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 173, in connect
return MySQLConnection(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 104, in __init__
self.connect(**kwargs)
File "/usr/local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 780, in connect
self._open_connection()
File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 285, in _open_connection
self._do_handshake()
File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 148, in _do_handshake
raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1129: Host '10.10.2.83' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'
```

**Comment by euan-forrester** [comment]
Can temporarily resolve by running the `FLUSH HOSTS;` SQL command: https://chartio.com/resources/tutorials/how-to-run-mysqladmin-flush-hosts-on-amazon-rds/

**Comment by euan-forrester** [comment]
Need a metric on this so we can alert

**Comment by euan-forrester** [comment]
Did this happen when I was working on the parameter cacheing, which resulted in incorrectly getting cached parameters until I got the encoding sorted out?

**Comment by euan-forrester** [comment]
Haven't seen this since, so it seems reasonable to assume that it happened because of a bug in parameter cacheing before it was fixed.

Added a handler for unhandled exceptions, and an alert so we'll get notified next time: https://github.com/euan-forrester/photo-recommender/pull/45
